"use client";
import {useEffect,useState} from "react";
const nav=["Beranda","Profil","Informasi","Kegiatan","Layanan","Komunitas","Pengumuman","Galeri","Kontak"];
const services=[["📄","Surat Pengantar","Ajukan surat secara online"],["📣","Pengaduan","Sampaikan aspirasi warga"],["🗓️","Agenda","Lihat kegiatan RT"],["📊","Polling","Suara warga"],["🏪","UMKM Warga","Produk lokal"],["🖼️","Galeri","Dokumentasi kegiatan"]];
const posts=[{name:"Budi Santoso",time:"12 menit lalu",text:"Besok pagi ada kerja bakti. Mari ikut menjaga lingkungan kita tetap bersih dan nyaman. 🌿",react:"24",comments:"8",avatar:"BS"},{name:"Siti Aminah",time:"1 jam lalu",text:"Ada yang tahu jadwal posyandu bulan ini? Saya lihat pengumumannya belum masuk.",react:"12",comments:"5",avatar:"SA"}];
export default function Home(){
 const [page,setPage]=useState("Beranda"); const [menu,setMenu]=useState(false); const [liked,setLiked]=useState<number[]>([]);\n useEffect(()=>{if("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(()=>{});},[]);
 const go=(p:string)=>{setPage(p);setMenu(false);window.scrollTo({top:0,behavior:"smooth"})};
 return <main>
  <header className="top"><div className="wrap nav"><button className="brand" onClick={()=>go("Beranda")}><img className="logoImg" src="/logo.svg" alt="Logo RT 01 RW 04"/><span><b>RT 01 / RW 04</b><small>DESA PEGANDEKAN</small></span></button><nav>{nav.map(n=><button className={page===n?"active":""} onClick={()=>go(n)} key={n}>{n}</button>)}</nav><div className="navRight"><button className="search">⌕</button><button className="login" onClick={()=>go("Login")}>Masuk</button><button className="hamb" onClick={()=>setMenu(!menu)}>☰</button></div></div>{menu&&<div className="mobileMenu">{nav.map(n=><button onClick={()=>go(n)} key={n}>{n}</button>)}<button onClick={()=>go("Login")}>Masuk</button></div>}</header>
  {page==="Beranda"?<HomePage go={go} liked={liked} setLiked={setLiked}/>:<FeaturePage page={page} go={go}/>}
  <footer><div className="wrap foot"><div><div className="footBrand"><span className="crest big">RT</span><div><b>RT 01 / RW 04</b><small>Dusun 2 Pegandekan</small></div></div><p>Portal digital warga untuk informasi, pelayanan, kegiatan, dan komunitas.</p></div><div><h4>Navigasi</h4><p>Profil · Informasi · Kegiatan<br/>Layanan · Komunitas · Galeri</p></div><div><h4>Lokasi</h4><p>Desa Pegandekan<br/>Kecamatan Kemangkon<br/>Kabupaten Purbalingga</p></div></div><div className="copyright">© 2026 RT 01 RW 04 Pegandekan · Dibangun untuk warga</div></footer>
 </main>
}
function HomePage({go,liked,setLiked}:{go:(p:string)=>void,liked:number[],setLiked:React.Dispatch<React.SetStateAction<number[]>>}){
 return <><section className="hero"><div className="wrap heroGrid"><div><div className="eyebrow">PORTAL DIGITAL WARGA</div><h1>RT 01 / RW 04<br/><span>Pegandekan</span></h1><p className="lead">Bersama membangun lingkungan yang <b>rukun, aman & sejahtera.</b></p><div className="location">📍 Dusun 2 · Desa Pegandekan · Kecamatan Kemangkon<br/>Kabupaten Purbalingga, Jawa Tengah</div><div className="actions"><button className="primary" onClick={()=>go("Komunitas")}>Masuk Komunitas →</button><button className="secondary" onClick={()=>go("Layanan")}>Layanan Warga</button></div></div><div className="heroArt"><div className="sun"/><div className="mountain m1"/><div className="mountain m2"/><div className="rice">🌾</div><div className="house">🏡</div><div className="artBadge"><span className="crest big">RT</span><b>01 / 04</b><small>PEGANDEKAN</small></div></div></div></section>
 <section className="section"><div className="wrap"><div className="sectionHead"><div><span className="eyebrow">INFORMASI TERBARU</span><h2>Pengumuman Warga</h2></div><button className="textBtn" onClick={()=>go("Pengumuman")}>Lihat semua →</button></div><div className="announce"><article><span className="tag">PENTING</span><h3>Kerja Bakti Lingkungan</h3><p>Minggu, 21 September 2026 · 07.00 WIB. Titik kumpul di balai RT.</p><button onClick={()=>go("Kegiatan")}>Selengkapnya →</button></article><article><span className="tag green">INFO</span><h3>Pendataan Warga 2026</h3><p>Pembaruan data warga dibuka sampai akhir bulan. Silakan cek profil.</p><button onClick={()=>go("Profil")}>Cek Data →</button></article><article className="quote"><span>“</span><p>Gotong royong bukan sekadar kegiatan, tapi cara kita menjaga rasa memiliki.</p><b>— Ketua RT 01</b></article></div></div></section>
 <section className="section pale"><div className="wrap"><div className="sectionHead"><div><span className="eyebrow">MUDAH & CEPAT</span><h2>Layanan Warga</h2></div><button className="textBtn" onClick={()=>go("Layanan")}>Semua layanan →</button></div><div className="services">{services.map(([i,t,d])=><button className="service" key={t} onClick={()=>go("Layanan")}><span>{i}</span><div><b>{t}</b><small>{d}</small></div><em>→</em></button>)}</div></div></section>
 <section className="section"><div className="wrap split"><div><span className="eyebrow">KOMUNITAS</span><h2>Suara Warga, Cerita Kita</h2><p className="muted">Berbagi kabar, berdiskusi, membuat aspirasi, polling, dan mengikuti story warga dalam satu tempat.</p><div className="chips"><span>💬 Diskusi</span><span>❤️ Reaksi</span><span>📊 Polling</span><span>📸 Story 24h</span></div><button className="primary" onClick={()=>go("Komunitas")}>Buka Feed Warga →</button></div><div className="feedMini">{posts.map((p,i)=><article className="post" key={p.name}><div className="avatar">{p.avatar}</div><div className="postBody"><div className="postMeta"><b>{p.name}</b><small>{p.time}</small></div><p>{p.text}</p><div className="postActions"><button onClick={()=>setLiked(x=>x.includes(i)?x.filter(n=>n!==i):[...x,i])}>{liked.includes(i)?"❤️":"🤍"} {Number(p.react)+(liked.includes(i)?1:0)}</button><button>💬 {p.comments}</button><button>↗ Bagikan</button></div></div></article>)}</div></div></section>
 <section className="banner"><div className="wrap bannerInner"><div><span className="eyebrow">LINGKUNGAN KITA</span><h2>Mari Jaga Kebersihan<br/>Lingkungan Kita</h2><p>Lingkungan bersih, warga sehat, keluarga nyaman.</p></div><div className="bannerIcon">🌱</div></div></section>
 </>}
function FeaturePage({page,go}:{page:string,go:(p:string)=>void}){
 const data:any={Profil:["Profil RT 01 / RW 04","Mengenal pengurus, wilayah, dan informasi dasar lingkungan."],Informasi:["Pusat Informasi","Pengumuman, berita warga, dan informasi penting terbaru."],Kegiatan:["Agenda & Kegiatan","Kerja bakti, rapat warga, posyandu, olahraga, dan kegiatan lainnya."],Layanan:["Layanan Warga","Ajukan surat pengantar, pengaduan, aspirasi, dan kebutuhan administrasi."],Komunitas:["Komunitas Warga","Feed warga · Story 24 jam · Aspirasi · Diskusi · Polling · Reaksi · Komentar bertingkat."],Pengumuman:["Pengumuman","Semua pengumuman resmi RT tersusun rapi dan mudah dicari."],Galeri:["Galeri Kegiatan","Dokumentasi kegiatan dan momen kebersamaan warga."],Kontak:["Kontak & Lokasi","Hubungi pengurus RT dan temukan lokasi lingkungan."],Login:["Masuk ke Portal Warga","Gunakan email atau akun Google untuk melanjutkan."]};
 const [tab,setTab]=useState("Feed Warga"); const [comment,setComment]=useState(""); const [sent,setSent]=useState(false);
 if(page==="Login")return <section className="auth"><div className="authCard"><span className="crest big">RT</span><h1>Selamat Datang</h1><p>Portal Digital RT 01 / RW 04 Pegandekan</p><input placeholder="Email"/><input placeholder="Kata sandi" type="password"/><button className="primary wide">Masuk</button><button className="google">G &nbsp; Lanjut dengan Google</button><button className="link">Lupa kata sandi?</button><hr/><p>Belum punya akun? <b>Daftar sekarang</b></p></div></section>;
 return <section className="page"><div className="wrap"><div className="pageHero"><div><span className="eyebrow">RT 01 / RW 04 · PEGANDEKAN</span><h1>{data[page]?.[0]||page}</h1><p>{data[page]?.[1]}</p></div><button className="secondary" onClick={()=>go("Beranda")}>← Kembali</button></div>
 {page==="Komunitas"?<Community tab={tab} setTab={setTab} comment={comment} setComment={setComment} sent={sent} setSent={setSent}/>:<Generic page={page}/>}
 </div></section>
}
function Community({tab,setTab,comment,setComment,sent,setSent}:{tab:string,setTab:any,comment:string,setComment:any,sent:boolean,setSent:any}){
 const tabs=["Feed Warga","Story 24h","Aspirasi","Diskusi","Polling"];
 return <div className="community"><div className="tabs">{tabs.map(t=><button className={tab===t?"selected":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>{tab==="Story 24h"?<div className="stories">{["🌄","👨‍🌾","🌱","🏡","🎉"].map((x,i)=><div className="story" key={i}><span>{x}</span><b>{["Budi","Siti","Agus","Rina","Doni"][i]}</b><small>18j</small></div>)}</div>:tab==="Aspirasi"?<div className="grid2"><div className="card"><span className="status">DITINJAU</span><h3>Perbaikan lampu jalan</h3><p>Beberapa titik penerangan perlu diperiksa.</p><div className="timeline"><span>✓ Diajukan</span><span>● Ditinjau</span><span>○ Dikoordinasikan</span><span>○ Selesai</span></div></div><div className="card"><span className="status done">SELESAI</span><h3>Saluran air depan balai</h3><p>Pembersihan telah selesai dilakukan.</p><div className="timeline"><span>✓ Diajukan</span><span>✓ Ditinjau</span><span>✓ Dikerjakan</span><span>✓ Selesai</span></div></div></div>:tab==="Polling"?<div className="card poll"><span className="eyebrow">POLLING WARGA</span><h2>Usulan kegiatan bulan depan?</h2>{["Kerja bakti","Senam pagi","Lomba antar-RT","Pelatihan UMKM"].map((x,i)=><button key={x} className="pollOpt"><span>{x}</span><b>{[42,26,19,13][i]}%</b></button>)}</div>:<div className="feed">{[1,2,3].map(i=><article className="card postFull" key={i}><div className="avatar">WR</div><div><div className="postMeta"><b>{i===1?"Budi Santoso":i===2?"Siti Aminah":"Admin RT 01"}</b><small>{i*17} menit lalu</small></div><p>{i===1?"Besok pagi kerja bakti. Titik kumpul pukul 07.00 di balai RT.":i===2?"Mari berbagi informasi positif dan saling membantu antarwarga.":"Pengingat: pendataan warga 2026 masih dibuka."}</p><div className="postActions"><button>❤️ 24</button><button>👍 12</button><button>💬 8</button><button>↗ Bagikan</button></div><div className="commentBox"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Tulis komentar..."/><button onClick={()=>{setSent(true);setComment("")}}>Kirim</button></div>{sent&&<small className="sent">Komentar dikirim pada prototype.</small>}<div className="reply">↳ <b>Rina:</b> Siap, ikut ya! <button>Balas</button></div></div></article>)}</div>}</div>
}
function Generic({page}:{page:string}){const cards={Profil:["👥","Pengurus RT","Ketua RT · Sekretaris · Bendahara · Koordinator"],Informasi:["📢","Informasi Terkini","Pengumuman resmi, berita warga, dan arsip informasi."],Kegiatan:["🗓️","Agenda Mendatang","Kerja bakti · Rapat warga · Posyandu · Olahraga"],Layanan:["🧾","Ajukan Layanan","Surat pengantar, pengaduan, aspirasi, dan administrasi warga."],Pengumuman:["📣","Pengumuman Resmi","Notifikasi penting dari pengurus RT."],Galeri:["🖼️","Dokumentasi","Foto kegiatan, lingkungan, dan kebersamaan warga."],Kontak:["📍","Hubungi Pengurus","WhatsApp · Email · Lokasi balai RT"]};const c:any=cards[page as keyof typeof cards]||["✨",page,"Fitur siap dikembangkan"];return <div className="grid3"><div className="featureCard"><span>{c[0]}</span><h2>{c[1]}</h2><p>{c[2]}</p><button className="primary">Buka fitur →</button></div><div className="featureCard"><span>🔐</span><h2>Akun & Keamanan</h2><p>Email verification · Google login · role warga/admin · moderasi.</p><button className="secondary">Pengaturan</button></div><div className="featureCard"><span>📱</span><h2>PWA</h2><p>Install ke perangkat, tampilan responsif, cache offline, dan siap notifikasi.</p><button className="secondary">Install App</button></div></div>}
