"use client";
import {useEffect,useState} from "react";
const nav=[["Beranda","fa-house"],["Profil","fa-users"],["Informasi","fa-circle-info"],["Kegiatan","fa-calendar-days"],["Layanan","fa-file-signature"],["Komunitas","fa-comments"],["Pengumuman","fa-bullhorn"],["Galeri","fa-images"],["Kontak","fa-location-dot"]] as const;
const Icon=({name}:{name:string})=><i className={`fa-solid ${name}`} aria-hidden="true"/>;
const services=[["fa-file-lines","Surat Pengantar","Ajukan surat secara online"],["fa-bullhorn","Pengaduan","Sampaikan aspirasi warga"],["fa-calendar-check","Agenda","Lihat kegiatan RT"],["fa-chart-pie","Polling","Suara warga"],["fa-store","UMKM Warga","Produk lokal"],["fa-images","Galeri","Dokumentasi kegiatan"]];
const posts=[{name:"Budi Santoso",time:"12 menit lalu",text:"Besok pagi ada kerja bakti. Mari ikut menjaga lingkungan kita tetap bersih dan nyaman. 🌿",react:"24",comments:"8",avatar:"BS"},{name:"Siti Aminah",time:"1 jam lalu",text:"Ada yang tahu jadwal posyandu bulan ini? Saya lihat pengumumannya belum masuk.",react:"12",comments:"5",avatar:"SA"}];
export default function Home(){
 const [page,setPage]=useState("Beranda"); const [menu,setMenu]=useState(false); const [liked,setLiked]=useState<number[]>([]); const [showSplash,setShowSplash]=useState(true);
 useEffect(()=>{if("serviceWorker" in navigator) navigator.serviceWorker.register("sw.js").catch(()=>{}); const t=window.setTimeout(()=>setShowSplash(false),1400); return()=>window.clearTimeout(t);},[]);
 const go=(p:string)=>{setPage(p);setMenu(false);window.scrollTo({top:0,behavior:"smooth"})};
 return <main>{showSplash&&<div className="appSplash"><div className="splashLogoWrap"><img src="https://i.ibb.co.com/TMpphB84/Chat-GPT-Image-Aug-1-2026-09-27-41-AM-removebg-preview.png" alt="Logo RT 01 RW 04"/></div><h2>RT 01 / RW 04</h2><p>Desa Pegandekan · Kecamatan Kemangkon</p><span><i></i></span></div>}
  <header className="top"><div className="wrap nav"><button className="brand" onClick={()=>go("Beranda")}><img className="logoImg" src="https://i.ibb.co.com/TMpphB84/Chat-GPT-Image-Aug-1-2026-09-27-41-AM-removebg-preview.png" alt="Logo RT 01 RW 04"/><span><b>RT 01 / RW 04</b><small>DESA PEGANDEKAN</small></span></button><nav>{nav.map(([n,ic])=><button className={page===n?"active":""} onClick={()=>go(n)} key={n}><Icon name={ic}/><span>{n}</span></button>)}</nav><div className="navRight"><button className="search" aria-label="Cari"><Icon name="fa-magnifying-glass"/></button><button className="login" onClick={()=>go("Login")}>Masuk</button><button className="hamb" aria-label="Menu" onClick={()=>setMenu(!menu)}><Icon name="fa-bars"/></button></div></div>{menu&&<div className="mobileMenu">{nav.map(([n,ic])=><button onClick={()=>go(n)} key={n}><Icon name={ic}/><span>{n}</span></button>)}<button onClick={()=>go("Login")}>Masuk</button></div>}</header>
  {page==="Beranda"?<HomePage go={go} liked={liked} setLiked={setLiked}/>:<FeaturePage page={page} go={go}/>}
  <footer><div className="wrap foot"><div><div className="footBrand"><img className="footLogo" src="https://i.ibb.co.com/TMpphB84/Chat-GPT-Image-Aug-1-2026-09-27-41-AM-removebg-preview.png" alt="Logo RT 01 RW 04"/><div><b>RT 01 / RW 04</b><small>Dusun 2 Pegandekan</small></div></div><p>Portal digital warga untuk informasi, pelayanan, kegiatan, dan komunitas.</p></div><div><h4>Navigasi</h4><p>Profil · Informasi · Kegiatan<br/>Layanan · Komunitas · Galeri</p></div><div><h4>Lokasi</h4><p>Desa Pegandekan<br/>Kecamatan Kemangkon<br/>Kabupaten Purbalingga</p></div></div><div className="copyright">© 2026 RT 01 RW 04 Pegandekan · Dibangun untuk warga</div></footer>
 </main>
}
function HomePage({go,liked,setLiked}:{go:(p:string)=>void,liked:number[],setLiked:React.Dispatch<React.SetStateAction<number[]>>}){
 return <><section className="hero"><div className="wrap heroGrid"><div><div className="eyebrow">PORTAL DIGITAL WARGA</div><h1>RT 01 / RW 04<br/><span>Pegandekan</span></h1><p className="lead">Bersama membangun lingkungan yang <b>rukun, aman & sejahtera.</b></p><div className="location"><Icon name="fa-location-dot"/> Dusun 2 · Desa Pegandekan · Kecamatan Kemangkon<br/>Kabupaten Purbalingga, Jawa Tengah</div><div className="actions"><button className="primary" onClick={()=>go("Komunitas")}><Icon name="fa-users"/> Masuk Komunitas</button><button className="secondary" onClick={()=>go("Layanan")}><Icon name="fa-file-signature"/> Layanan Warga</button></div></div><div className="heroArt"><div className="sun"/><div className="mountain m1"/><div className="mountain m2"/><div className="rice">🌾</div><div className="house">🏡</div><div className="artBadge"><span className="crest big">RT</span><b>01 / 04</b><small>PEGANDEKAN</small></div></div></div></section>
 <section className="section"><div className="wrap"><div className="sectionHead"><div><span className="eyebrow">INFORMASI TERBARU</span><h2>Pengumuman Warga</h2></div><button className="textBtn" onClick={()=>go("Pengumuman")}>Lihat semua →</button></div><div className="announce"><article><span className="tag">PENTING</span><h3>Kerja Bakti Lingkungan</h3><p>Minggu, 21 September 2026 · 07.00 WIB. Titik kumpul di balai RT.</p><button onClick={()=>go("Kegiatan")}>Selengkapnya →</button></article><article><span className="tag green">INFO</span><h3>Pendataan Warga 2026</h3><p>Pembaruan data warga dibuka sampai akhir bulan. Silakan cek profil.</p><button onClick={()=>go("Profil")}>Cek Data →</button></article><article className="quote"><span>“</span><p>Gotong royong bukan sekadar kegiatan, tapi cara kita menjaga rasa memiliki.</p><b>— Ketua RT 01</b></article></div></div></section>
 <section className="section pale"><div className="wrap"><div className="sectionHead"><div><span className="eyebrow">MUDAH & CEPAT</span><h2>Layanan Warga</h2></div><button className="textBtn" onClick={()=>go("Layanan")}>Semua layanan →</button></div><div className="services">{services.map(([i,t,d])=><button className="service" key={t} onClick={()=>go("Layanan")}><span className="serviceIcon"><Icon name={i}/></span><div><b>{t}</b><small>{d}</small></div><em><Icon name="fa-arrow-right"/></em></button>)}</div></div></section>
 <section className="section"><div className="wrap split"><div><span className="eyebrow">KOMUNITAS</span><h2>Suara Warga, Cerita Kita</h2><p className="muted">Berbagi kabar, berdiskusi, membuat aspirasi, polling, dan mengikuti story warga dalam satu tempat.</p><div className="chips"><span><Icon name="fa-comments"/> Diskusi</span><span><Icon name="fa-heart"/> Reaksi</span><span><Icon name="fa-chart-pie"/> Polling</span><span><Icon name="fa-camera"/> Story 24h</span></div><button className="primary" onClick={()=>go("Komunitas")}><Icon name="fa-comments"/> Buka Feed Warga</button></div><div className="feedMini">{posts.map((p,i)=><article className="post" key={p.name}><div className="avatar">{p.avatar}</div><div className="postBody"><div className="postMeta"><b>{p.name}</b><small>{p.time}</small></div><p>{p.text}</p><div className="postActions"><button onClick={()=>setLiked(x=>x.includes(i)?x.filter(n=>n!==i):[...x,i])}><Icon name="fa-heart"/> {Number(p.react)+(liked.includes(i)?1:0)}</button><button><Icon name="fa-comment"/> {p.comments}</button><button><Icon name="fa-share-nodes"/> Bagikan</button></div></div></article>)}</div></div></section>
 <section className="banner"><div className="wrap bannerInner"><div><span className="eyebrow">LINGKUNGAN KITA</span><h2>Mari Jaga Kebersihan<br/>Lingkungan Kita</h2><p>Lingkungan bersih, warga sehat, keluarga nyaman.</p></div><div className="bannerIcon"><Icon name="fa-seedling"/></div></div></section>
 </>}
function FeaturePage({page,go}:{page:string,go:(p:string)=>void}){
 const data:any={Profil:["Profil RT 01 / RW 04","Mengenal pengurus, wilayah, dan informasi dasar lingkungan."],Informasi:["Pusat Informasi","Pengumuman, berita warga, dan informasi penting terbaru."],Kegiatan:["Agenda & Kegiatan","Kerja bakti, rapat warga, posyandu, olahraga, dan kegiatan lainnya."],Layanan:["Layanan Warga","Ajukan surat pengantar, pengaduan, aspirasi, dan kebutuhan administrasi."],Komunitas:["Komunitas Warga","Feed warga · Story 24 jam · Aspirasi · Diskusi · Polling · Reaksi · Komentar bertingkat."],Pengumuman:["Pengumuman","Semua pengumuman resmi RT tersusun rapi dan mudah dicari."],Galeri:["Galeri Kegiatan","Dokumentasi kegiatan dan momen kebersamaan warga."],Kontak:["Kontak & Lokasi","Hubungi pengurus RT dan temukan lokasi lingkungan."],Login:["Masuk ke Portal Warga","Gunakan email atau akun Google untuk melanjutkan."]};
 const [tab,setTab]=useState("Feed Warga"); const [comment,setComment]=useState(""); const [sent,setSent]=useState(false);
 if(page==="Login")return <section className="auth"><div className="authCard"><img className="authLogo" src="https://i.ibb.co.com/TMpphB84/Chat-GPT-Image-Aug-1-2026-09-27-41-AM-removebg-preview.png" alt="Logo RT 01 RW 04"/><h1>Selamat Datang</h1><p>Portal Digital RT 01 / RW 04 Pegandekan</p><input placeholder="Email"/><input placeholder="Kata sandi" type="password"/><button className="primary wide">Masuk</button><button className="google"><Icon name="fa-google"/> Lanjut dengan Google</button><button className="link"><Icon name="fa-key"/> Lupa kata sandi?</button><hr/><p>Belum punya akun? <b>Daftar sekarang</b></p></div></section>;
 return <section className="page"><div className="wrap">{page==="Komunitas"?<Community tab={tab} setTab={setTab} comment={comment} setComment={setComment} sent={sent} setSent={setSent}/>:<><div className="pageHero"><div><span className="eyebrow">RT 01 / RW 04 · PEGANDEKAN</span><h1>{data[page]?.[0]||page}</h1><p>{data[page]?.[1]}</p></div><button className="secondary" onClick={()=>go("Beranda")}><Icon name="fa-arrow-left"/> Kembali</button></div><Generic page={page}/></>}</div></section>
}
function Community({tab,setTab,comment,setComment,sent,setSent}:{tab:string,setTab:any,comment:string,setComment:any,sent:boolean,setSent:any}){
 const tabs=[["Feed Warga","fa-house"],["Aspirasi","fa-lightbulb"],["Diskusi","fa-comments"],["Polling","fa-square-poll-vertical"]] as const;
 const stories=[["BS","Budi","fa-mountain-sun"],["SA","Siti","fa-seedling"],["AR","Agus","fa-person"],["RN","Rina","fa-house"],["DN","Doni","fa-champagne-glasses"]];
 const reactions=[["👍","Suka"],["❤️","Love"],["😆","Haha"],["😮","Wow"],["😢","Sedih"],["😡","Marah"]] as const;
 const stickers=["😂","😍","🥰","🤗","🎉","👏","🔥","🙏","🤣","😘"];
 const seedFeed=[
  {id:1,name:"Budi Santoso",initial:"BS",time:"18 menit",text:"Ngikutin trend jajanan warga. Ada yang punya rekomendasi jajanan enak di sekitar Pegandekan?",image:"https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1000&q=80",likes:55,comments:[{name:"Reno Bangkit",initial:"RB",text:"Kang, aku bikin koleksi processing terus ya? Solusi dong",time:"13 jam",reaction:"",image:"",sticker:""}],shares:19,feeling:"",reaction:""},
  {id:2,name:"Siti Aminah",initial:"SA",time:"1 jam",text:"Besok pagi ada kerja bakti. Mari ikut menjaga lingkungan kita tetap bersih dan nyaman. 🌿",image:"",likes:12,comments:[],shares:3,feeling:"senang",reaction:""}
 ];
 const [feed,setFeed]=useState<any[]>(()=>{try{return JSON.parse(localStorage.getItem("rt-feed")||"null")||seedFeed}catch{return seedFeed}});
 const [draft,setDraft]=useState(""); const [feeling,setFeeling]=useState(""); const [photo,setPhoto]=useState(""); const [showFeelings,setShowFeelings]=useState(false);
 const [reply,setReply]=useState<Record<number,string>>({}); const [commentMedia,setCommentMedia]=useState<Record<number,string>>({}); const [commentSticker,setCommentSticker]=useState<Record<number,string>>({});
 const [replyTo,setReplyTo]=useState<Record<number,number|null>>({}); const [search,setSearch]=useState(""); const [selectedPoll,setSelectedPoll]=useState<string>(()=>localStorage.getItem("rt-poll")||"");
 const [reactionOpen,setReactionOpen]=useState<number|null>(null); const [commentReactionOpen,setCommentReactionOpen]=useState<string|null>(null);
 const [aspirations,setAspirations]=useState<any[]>(()=>{try{return JSON.parse(localStorage.getItem("rt-aspirations")||"[]")}catch{return[]}});
 const [discussions,setDiscussions]=useState<any[]>(()=>{try{return JSON.parse(localStorage.getItem("rt-discussions")||"[]")}catch{return[]}});
 const [modal,setModal]=useState<"aspiration"|"discussion"|null>(null); const [modalText,setModalText]=useState("");
 useEffect(()=>{localStorage.setItem("rt-feed",JSON.stringify(feed));localStorage.setItem("rt-aspirations",JSON.stringify(aspirations));localStorage.setItem("rt-discussions",JSON.stringify(discussions));localStorage.setItem("rt-poll",selectedPoll)},[feed,aspirations,discussions,selectedPoll]);
 const readFile=(file:any,cb:any)=>{if(!file)return;if(file.size>4*1024*1024){alert("File maksimal 4 MB.");return}const r=new FileReader();r.onload=()=>cb(String(r.result));r.readAsDataURL(file)};
 const pickPhoto=(e:any)=>readFile(e.target.files?.[0],setPhoto);
 const pickCommentImage=(id:number,e:any)=>readFile(e.target.files?.[0],(v:string)=>setCommentMedia(x=>({...x,[id]:v})));
 const addPost=()=>{if(!draft.trim()&&!photo)return;setFeed(x=>[{id:Date.now(),name:"Anda",initial:"AN",time:"baru saja",text:draft.trim(),image:photo,likes:0,comments:[],shares:0,feeling,reaction:""},...x]);setDraft("");setPhoto("");setFeeling("");setShowFeelings(false)};
 const setPostReaction=(id:number,r:string)=>{setFeed(x=>x.map(p=>p.id===id?{...p,reaction:p.reaction===r?"":r}:p));setReactionOpen(null)};
 const setCommentReaction=(id:number,j:number,r:string)=>{setFeed(x=>x.map(p=>p.id===id?{...p,comments:p.comments.map((co:any,i:number)=>i===j?{...co,reaction:co.reaction===r?"":r}:co)}:p));setCommentReactionOpen(null)};
 const addComment=(id:number)=>{const text=(reply[id]||"").trim(), media=commentMedia[id]||"", sticker=commentSticker[id]||"";if(!text&&!media&&!sticker)return;setFeed(x=>x.map(p=>p.id===id?{...p,comments:[...p.comments,{name:"Anda",initial:"AN",text,time:"baru saja",image:media,sticker,reaction:"",replyTo:replyTo[id]??null}]}:p));setReply(x=>({...x,[id]:""}));setCommentMedia(x=>({...x,[id]:""}));setCommentSticker(x=>({...x,[id]:""}));setReplyTo(x=>({...x,[id]:null}));setSent(true);setTimeout(()=>setSent(false),1800)};
 const share=(p:any)=>{const text=p.text||"Kiriman warga";if(navigator.share)navigator.share({title:"Komunitas Warga",text}).catch(()=>{});else navigator.clipboard?.writeText(text).then(()=>alert("Teks kiriman disalin."))};
 const submitModal=()=>{if(!modalText.trim())return;if(modal==="aspiration")setAspirations(x=>[{id:Date.now(),title:modalText.trim(),status:"DITINJAU"},...x]);if(modal==="discussion")setDiscussions(x=>[{id:Date.now(),title:modalText.trim(),replies:0},...x]);setModal(null);setModalText("")};
 const visible=feed.filter(p=>!search||p.name.toLowerCase().includes(search.toLowerCase())||p.text.toLowerCase().includes(search.toLowerCase()));
 const reactionLabel=(r:string)=>reactions.find(x=>x[0]===r)?.[1]||"Suka";
 return <div className="communityShell">
  <div className="communityTop"><div className="communityTitle"><div className="communityAvatar"><Icon name="fa-users"/></div><div><b>Komunitas Warga</b><small>RT 01 / RW 04 · Pegandekan</small></div></div><div className="communitySearchWrap"><Icon name="fa-magnifying-glass"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari warga atau postingan"/></div></div>
  <div className="communityTabs">{tabs.map(([t,ic])=><button className={tab===t?"selected":""} onClick={()=>setTab(t)} key={t}><Icon name={ic}/><span>{t}</span></button>)}</div>
  {tab==="Aspirasi"?<div className="communityCard aspirationPanel"><div className="panelTitle"><div><b>Aspirasi Warga</b><small>Sampaikan kebutuhan lingkungan</small></div><button onClick={()=>setModal("aspiration")}><Icon name="fa-plus"/> Buat aspirasi</button></div>{aspirations.length===0?<div className="emptyState"><Icon name="fa-lightbulb"/><p>Belum ada aspirasi baru.</p><button className="primary" onClick={()=>setModal("aspiration")}>Tulis Aspirasi</button></div>:aspirations.map(a=><div className="aspirationItem" key={a.id}><span className="status"><Icon name="fa-clock"/> {a.status}</span><h3>{a.title}</h3><p>Diajukan oleh Anda · baru saja</p><div className="timeline"><span>✓ Diajukan</span><span>● Ditinjau</span><span>○ Dikoordinasikan</span><span>○ Selesai</span></div></div>)}</div>
  :tab==="Polling"?<div className="communityCard poll"><div className="panelTitle"><div><span className="eyebrow"><Icon name="fa-square-poll-vertical"/> POLLING WARGA</span><h2>Usulan kegiatan bulan depan?</h2><small>Pilih satu opsi. Pilihan tersimpan di perangkat Anda.</small></div></div>{["Kerja bakti","Senam pagi","Lomba antar-RT","Pelatihan UMKM"].map((x,i)=><button key={x} className={"pollOpt "+(selectedPoll===x?"chosen":"")} onClick={()=>setSelectedPoll(x)}><span><i className={selectedPoll===x?"fa-solid fa-circle-check":"fa-regular fa-circle"}/> {x}</span><b>{[42,26,19,13][i]}%</b></button>)}{selectedPoll&&<div className="pollSaved"><Icon name="fa-circle-check"/> Pilihan Anda: <b>{selectedPoll}</b></div>}</div>
  :tab==="Diskusi"?<div className="communityCard discussion"><div className="panelTitle"><div><b>Diskusi Warga</b><small>Topik dan percakapan lingkungan</small></div><button onClick={()=>setModal("discussion")}><Icon name="fa-plus"/> Topik baru</button></div>{[...discussions,{id:"seed1",title:"Persiapan kerja bakti Minggu",replies:8},{id:"seed2",title:"Ide kegiatan pemuda RT",replies:14}].map(d=><div className="discussionItem" key={d.id}><Icon name="fa-comments"/><div><b>{d.title}</b><p>{d.replies} balasan · aktif baru saja</p></div><button aria-label="Buka diskusi" onClick={()=>alert("Ruang diskusi untuk topik ini siap digunakan.")}>›</button></div>)}</div>
  :<div className="feedColumn">
   <div className="composer communityCard"><div className="composerAvatar">AN</div><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Apa yang ingin kamu bagikan, warga?"/>{photo&&<div className="uploadPreview"><img src={photo} alt="Pratinjau foto"/><button onClick={()=>setPhoto("")}><Icon name="fa-xmark"/></button></div>}{feeling&&<div className="feelingChip"><Icon name="fa-face-smile"/> Sedang {feeling}</div>}<div className="composerTools"><label><Icon name="fa-image"/> Foto/Video<input type="file" accept="image/*" onChange={pickPhoto}/></label><button onClick={()=>setShowFeelings(x=>!x)}><Icon name="fa-face-smile"/> Perasaan</button><button onClick={()=>setTab("Aspirasi")}><Icon name="fa-bullhorn"/> Aspirasi</button><button className="postBtn" onClick={addPost} disabled={!draft.trim()&&!photo}>Posting</button></div>{showFeelings&&<div className="feelingMenu">{["senang","bersyukur","semangat","sedih","marah"].map(x=><button key={x} onClick={()=>{setFeeling(x);setShowFeelings(false)}}>😊 {x}</button>)}</div>}</div>
   <div className="communityCard storyStrip"><div className="storyAdd"><div className="storyAddIcon"><Icon name="fa-plus"/></div><b>Foto Warga</b><small>Upload foto di feed</small></div>{stories.slice(1).map(([initial,name,ic])=><div className="storyMini" key={name}><div className="storyMiniBg"><Icon name={ic}/></div><b>{name}</b></div>)}</div>
   {visible.map(p=><article className="communityCard socialPost" key={p.id}><div className="socialHeader"><div className="socialAvatar">{p.initial}</div><div className="socialIdentity"><b>{p.name}</b><small>{p.time} · <Icon name="fa-earth-asia"/> {p.feeling&&"· "+p.feeling}</small></div><button className="more" onClick={()=>{if(confirm("Hapus postingan ini?"))setFeed(x=>x.filter(v=>v.id!==p.id))}}><Icon name="fa-ellipsis"/></button></div><p className="socialText">{p.text}</p>{p.image&&<div className="postImage"><img src={p.image} alt="Kiriman warga"/></div>}<div className="postStats"><span>{p.reaction||"👍"} {p.likes+(p.reaction?1:0)}</span><span>{p.comments.length} komentar · {p.shares} dibagikan</span></div>
    <div className="socialActions reactionActionWrap"><button className={p.reaction?"actionActive reactionChosen":""} onClick={()=>setReactionOpen(reactionOpen===p.id?null:p.id)}><span className="reactionButtonIcon">{p.reaction||"👍"}</span> {p.reaction?reactionLabel(p.reaction):"Suka"}</button>{reactionOpen===p.id&&<div className="reactionPicker">{reactions.map(([r,label])=><button title={label} key={r} onClick={()=>setPostReaction(p.id,r)}>{r}<small>{label}</small></button>)}</div>}<button onClick={()=>document.getElementById("reply-"+p.id)?.focus()}><Icon name="fa-comment"/> Komentar</button><button onClick={()=>{setFeed(x=>x.map(v=>v.id===p.id?{...v,shares:v.shares+1}:v));share(p)}}><Icon name="fa-share"/> Bagikan</button></div>
    <div className="commentTop"><span>↕ Terbaru</span><span>{p.comments.length} komentar</span></div>
    {p.comments.map((co:any,j:number)=><div className="socialComment" key={j}><div className="commentAvatar">{co.initial}</div><div className="commentBody"><b>{co.name}</b><small>{co.time}{co.replyTo!=null?" · membalas komentar":""}</small>{co.text&&<p>{co.text}</p>}{co.sticker&&<div className="commentSticker">{co.sticker}</div>}{co.image&&<img className="commentImage" src={co.image} alt="Gambar komentar"/>}<div className="commentActions reactionActionWrap"><button className={co.reaction?"commentReacted":""} onClick={()=>setCommentReactionOpen(commentReactionOpen===p.id+"-"+j?null:p.id+"-"+j)}><span>{co.reaction||"👍"}</span> {co.reaction?reactionLabel(co.reaction):"Suka"}</button>{commentReactionOpen===p.id+"-"+j&&<div className="reactionPicker commentPicker">{reactions.map(([r,label])=><button title={label} key={r} onClick={()=>setCommentReaction(p.id,j,r)}>{r}<small>{label}</small></button>)}</div>}<button onClick={()=>{setReplyTo(x=>({...x,[p.id]:j}));document.getElementById("reply-"+p.id)?.focus()}}>↩ Balas</button></div></div></div>)}
    <div className="commentInput"><div className="commentAvatar">AN</div><div className="commentComposer"><input id={"reply-"+p.id} value={reply[p.id]||""} onChange={e=>setReply(x=>({...x,[p.id]:e.target.value}))} onKeyDown={e=>e.key==="Enter"&&addComment(p.id)} placeholder={replyTo[p.id]!=null?"Membalas komentar...":"Tulis komentar..."}/><div className="commentTools"><button onClick={()=>setCommentSticker(x=>({...x,[p.id]:x[p.id]?"":"😂"}))}>😊</button><button onClick={()=>document.getElementById("comment-image-"+p.id)?.click()}>🖼️</button><input id={"comment-image-"+p.id} hidden type="file" accept="image/*" onChange={e=>pickCommentImage(p.id,e)}/><button onClick={()=>setCommentSticker(x=>({...x,[p.id]:x[p.id]?"":"🎉"}))}>🎉</button><button onClick={()=>addComment(p.id)}><Icon name="fa-paper-plane"/></button></div></div></div>
    {(commentSticker[p.id]||commentMedia[p.id])&&<div className="commentAttachPreview">{commentSticker[p.id]&&<span>{commentSticker[p.id]}</span>}{commentMedia[p.id]&&<img src={commentMedia[p.id]} alt="Pratinjau komentar"/>}<button onClick={()=>{setCommentSticker(x=>({...x,[p.id]:""}));setCommentMedia(x=>({...x,[p.id]:""}))}}>×</button></div>}{sent&&<small className="sent">Komentar berhasil dikirim.</small>}</article>)}
   {visible.length===0&&<div className="communityCard emptyState"><Icon name="fa-magnifying-glass"/><p>Postingan tidak ditemukan.</p></div>}
  </div>}
  {modal&&<div className="modalBackdrop" onClick={()=>setModal(null)}><div className="modalCard" onClick={e=>e.stopPropagation()}><button className="modalClose" onClick={()=>setModal(null)}><Icon name="fa-xmark"/></button><h3>{modal==="aspiration"?"Buat Aspirasi Warga":"Buat Topik Diskusi"}</h3><textarea value={modalText} onChange={e=>setModalText(e.target.value)} placeholder={modal==="aspiration"?"Contoh: lampu jalan di gang perlu diperbaiki":"Tulis topik yang ingin dibahas warga..."}/><button className="primary wide" onClick={submitModal}>Publikasikan</button></div></div>}
 </div>
}
function Generic({page}:{page:string}){const cards={Profil:["fa-users","Pengurus RT","Ketua RT · Sekretaris · Bendahara · Koordinator"],Informasi:["fa-circle-info","Informasi Terkini","Pengumuman resmi, berita warga, dan arsip informasi."],Kegiatan:["fa-calendar-days","Agenda Mendatang","Kerja bakti · Rapat warga · Posyandu · Olahraga"],Layanan:["fa-file-signature","Ajukan Layanan","Surat pengantar, pengaduan, aspirasi, dan administrasi warga."],Pengumuman:["fa-bullhorn","Pengumuman Resmi","Notifikasi penting dari pengurus RT."],Galeri:["fa-images","Dokumentasi","Foto kegiatan, lingkungan, dan kebersamaan warga."],Kontak:["fa-location-dot","Hubungi Pengurus","WhatsApp · Email · Lokasi balai RT"]};const c:any=cards[page as keyof typeof cards]||["fa-wand-magic-sparkles",page,"Fitur siap dikembangkan"];return <div className="grid3"><div className="featureCard"><span><Icon name={c[0]}/></span><h2>{c[1]}</h2><p>{c[2]}</p><button className="primary">Buka fitur <Icon name="fa-arrow-right"/></button></div><div className="featureCard"><span><Icon name="fa-shield-halved"/></span><h2>Akun & Keamanan</h2><p>Email verification · Google login · role warga/admin · moderasi.</p><button className="secondary">Pengaturan</button></div><div className="featureCard"><span><Icon name="fa-mobile-screen-button"/></span><h2>PWA</h2><p>Install ke perangkat, tampilan responsif, cache offline, dan siap notifikasi.</p><button className="secondary">Install App <Icon name="fa-download"/></button></div></div>}
