"use client";
import {useEffect,useState} from "react";
const nav=[["Beranda","fa-house"],["Profil","fa-users"],["Informasi","fa-circle-info"],["Kegiatan","fa-calendar-days"],["Layanan","fa-file-signature"],["Komunitas","fa-comments"],["Pengumuman","fa-bullhorn"],["Galeri","fa-images"],["Kontak","fa-location-dot"]] as const;
const Icon=({name}:{name:string})=><i className={`fa-solid ${name}`} aria-hidden="true"/>;
const services=[["fa-file-lines","Surat Pengantar","Ajukan surat secara online"],["fa-bullhorn","Pengaduan","Sampaikan aspirasi warga"],["fa-calendar-check","Agenda","Lihat kegiatan RT"],["fa-chart-pie","Polling","Suara warga"],["fa-store","UMKM Warga","Produk lokal"],["fa-images","Galeri","Dokumentasi kegiatan"]];
const posts=[{name:"Budi Santoso",time:"12 menit lalu",text:"Besok pagi ada kerja bakti. Mari ikut menjaga lingkungan kita tetap bersih dan nyaman. 🌿",react:"24",comments:"8",avatar:"BS"},{name:"Siti Aminah",time:"1 jam lalu",text:"Ada yang tahu jadwal posyandu bulan ini? Saya lihat pengumumannya belum masuk.",react:"12",comments:"5",avatar:"SA"}];
export default function Home(){
 const [page,setPage]=useState("Beranda"); const [menu,setMenu]=useState(false); const [liked,setLiked]=useState<number[]>([]); const [showSplash,setShowSplash]=useState(true);
 useEffect(()=>{if("serviceWorker" in navigator) navigator.serviceWorker.register("sw.js").catch(()=>{}); const t=window.setTimeout(()=>setShowSplash(false),1400); return()=>window.clearTimeout(t);},[]);
 const go=(p:string)=>{setPage(p);setMenu(false);window.scrollTo({top:0,behavior:"smooth"})};
 return <main>{showSplash&&<div className="appSplash"><div className="splashLogoWrap"><img src="https://i.ibb.co.com/TMpphB84/Chat-GPT-Image-Aug-1-2026-09-27-41-AM-removebg-preview.png" alt="Logo RT 01 RW 04"/></div><h2>RT 01 / RW 04</h2><p>Desa Pegandekan · Kecamatan Kemangkon</p><span><i></i></span></div>}
  <header className="top"><div className="wrap nav"><button className="brand" onClick={()=>go("Beranda")}><img className="logoImg" src="https://i.ibb.co.com/TMpphB84/Chat-GPT-Image-Aug-1-2026-09-27-41-AM-removebg-preview.png" alt="Logo RT 01 RW 04"/><span><b>RT 01 / RW 04</b><small>DESA PEGANDEKAN</small></span></button><nav>{nav.map(([n,ic])=><button className={page===n?"active":""} onClick={()=>go(n)} key={n}><Icon name={ic}/><span>{n}</span></button>)}</nav><div className="navRight"><button className="search" aria-label="Cari"><Icon name="fa-magnifying-glass"/></button><button className="login" onClick={()=>go("Login")}>Masuk</button><button className="hamb" aria-label="Menu" onClick={()=>setMenu(!menu)}><Icon name="fa-bars"/></button></div></div>{menu&&<div className="mobileMenu">{nav.map(([n,ic])=><button onClick={()=>go(n)} key={n}><Icon name={ic}/><span>{n}</span></button>)}<button onClick={()=>go("Login")}>Masuk</button></div>}</header>
  {page==="Beranda"?<HomePage go={go} liked={liked} setLiked={setLiked}/>:<FeaturePage page={page} go={go}/>}
  <footer><div className="wrap foot"><div><div className="footBrand"><img className="footLogo" src="https://i.ibb.co.com/TMpphB84/Chat-GPT-Image-Aug-1-2026-09-27-41-AM-removebg-preview.png" alt="Logo RT 01 RW 04"/><div><b>RT 01 / RW 04</b><small>Dusun 2 Pegandekan</small></div></div><p>Portal digital warga untuk informasi, pelayanan, kegiatan, dan komunitas.</p></div><div><h4>Navigasi</h4><p>Profil · Informasi · Kegiatan<br/>Layanan · Komunitas · Galeri</p></div><div><h4>Lokasi</h4><p>Desa Pegandekan<br/>Kecamatan Kemangkon<br/>Kabupaten Purbalingga</p></div></div><div className="copyright">© 2026 RT 01 RW 04 Pegandekan · Dibangun untuk warga</div></footer>
 </main>
}
function HomePage({go,liked,setLiked}:{go:(p:string)=>void,liked:number[],setLiked:React.Dispatch<React.SetStateAction<number[]>>}){
 return <><section className="hero"><div className="wrap heroGrid"><div><div className="eyebrow">PORTAL DIGITAL WARGA</div><h1>RT 01 / RW 04<br/><span>Pegandekan</span></h1><p className="lead">Bersama membangun lingkungan yang <b>rukun, aman & sejahtera.</b></p><div className="location"><Icon name="fa-location-dot"/> Dusun 2 · Desa Pegandekan · Kecamatan Kemangkon<br/>Kabupaten Purbalingga, Jawa Tengah</div><div className="actions"><button className="primary" onClick={()=>go("Komunitas")}><Icon name="fa-users"/> Masuk Komunitas</button><button className="secondary" onClick={()=>go("Layanan")}><Icon name="fa-file-signature"/> Layanan Warga</button></div></div><div className="heroArt"><div className="sun"/><div className="mountain m1"/><div className="mountain m2"/><div className="rice">🌾</div><div className="house">🏡</div><div className="artBadge"><span className="crest big">RT</span><b>01 / 04</b><small>PEGANDEKAN</small></div></div></div></section>
 <section className="section"><div className="wrap"><div className="sectionHead"><div><span className="eyebrow">INFORMASI TERBARU</span><h2>Pengumuman Warga</h2></div><button className="textBtn" onClick={()=>go("Pengumuman")}>Lihat semua →</button></div><div className="announce"><article><span className="tag">PENTING</span><h3>Kerja Bakti Lingkungan</h3><p>Minggu, 21 September 2026 · 07.00 WIB. Titik kumpul di balai RT.</p><button onClick={()=>go("Kegiatan")}>Selengkapnya →</button></article><article><span className="tag green">INFO</span><h3>Pendataan Warga 2026</h3><p>Pembaruan data warga dibuka sampai akhir bulan. Silakan cek profil.</p><button onClick={()=>go("Profil")}>Cek Data →</button></article><article className="quote"><span>“</span><p>Gotong royong bukan sekadar kegiatan, tapi cara kita menjaga rasa memiliki.</p><b>— Ketua RT 01</b></article></div></div></section>
 <section className="section pale"><div className="wrap"><div className="sectionHead"><div><span className="eyebrow">MUDAH & CEPAT</span><h2>Layanan Warga</h2></div><button className="textBtn" onClick={()=>go("Layanan")}>Semua layanan →</button></div><div className="services">{services.map(([i,t,d])=><button className="service" key={t} onClick={()=>go("Layanan")}><span className="serviceIcon"><Icon name={i}/></span><div><b>{t}</b><small>{d}</small></div><em><Icon name="fa-arrow-right"/></em></button>)}</div></div></section>
 <section className="section"><div className="wrap split"><div><span className="eyebrow">KOMUNITAS</span><h2>Suara Warga, Cerita Kita</h2><p className="muted">Berbagi kabar, berdiskusi, membuat aspirasi, polling, dan mengikuti story warga dalam satu tempat.</p><div className="chips"><span><Icon name="fa-comments"/> Diskusi</span><span><Icon name="fa-heart"/> Reaksi</span><span><Icon name="fa-chart-pie"/> Polling</span><span><Icon name="fa-camera"/> Story 24h</span></div><button className="primary" onClick={()=>go("Komunitas")}><Icon name="fa-comments"/> Buka Feed Warga</button></div><div className="feedMini">{posts.map((p,i)=><article className="post" key={p.name}><div className="avatar">{p.avatar}</div><div className="postBody"><div className="postMeta"><b>{p.name}</b><small>{p.time}</small></div><p>{p.text}</p><div className="postActions"><button onClick={()=>setLiked(x=>x.includes(i)?x.filter(n=>n!==i):[...x,i])}><Icon name="fa-heart"/> {Number(p.react)+(liked.includes(i)?1:0)}</button><button><Icon name="fa-comment"/> {p.comments}</button><button><Icon name="fa-share-nodes"/> Bagikan</button></div></div></article>)}</div></div></section>
 <section className="banner"><div className="wrap bannerInner"><div><span className="eyebrow">LINGKUNGAN KITA</span><h2>Mari Jaga Kebersihan<br/>Lingkungan Kita</h2><p>Lingkungan bersih, warga sehat, keluarga nyaman.</p></div><div className="bannerIcon"><Icon name="fa-seedling"/></div></div></section>
 </>}
function FeaturePage({page,go}:{page:string,go:(p:string)=>void}){
 const data:any={Profil:["Profil RT 01 / RW 04","Mengenal pengurus, wilayah, dan informasi dasar lingkungan."],Informasi:["Pusat Informasi","Pengumuman, berita warga, dan informasi penting terbaru."],Kegiatan:["Agenda & Kegiatan","Kerja bakti, rapat warga, posyandu, olahraga, dan kegiatan lainnya."],Layanan:["Layanan Warga","Ajukan surat pengantar, pengaduan, aspirasi, dan kebutuhan administrasi."],Komunitas:["Komunitas Warga","Feed warga · Story 24 jam · Aspirasi · Diskusi · Polling · Reaksi · Komentar bertingkat."],Pengumuman:["Pengumuman","Semua pengumuman resmi RT tersusun rapi dan mudah dicari."],Galeri:["Galeri Kegiatan","Dokumentasi kegiatan dan momen kebersamaan warga."],Kontak:["Kontak & Lokasi","Hubungi pengurus RT dan temukan lokasi lingkungan."],Login:["Masuk ke Portal Warga","Gunakan email atau akun Google untuk melanjutkan."]};
 const [tab,setTab]=useState("Feed Warga"); const [comment,setComment]=useState(""); const [sent,setSent]=useState(false);
 if(page==="Login")return <section className="auth"><div className="authCard"><img className="authLogo" src="https://i.ibb.co.com/TMpphB84/Chat-GPT-Image-Aug-1-2026-09-27-41-AM-removebg-preview.png" alt="Logo RT 01 RW 04"/><h1>Selamat Datang</h1><p>Portal Digital RT 01 / RW 04 Pegandekan</p><input placeholder="Email"/><input placeholder="Kata sandi" type="password"/><button className="primary wide">Masuk</button><button className="google"><Icon name="fa-google"/> Lanjut dengan Google</button><button className="link"><Icon name="fa-key"/> Lupa kata sandi?</button><hr/><p>Belum punya akun? <b>Daftar sekarang</b></p></div></section>;
 return <section className="page"><div className="wrap"><div className="pageHero"><div><span className="eyebrow">RT 01 / RW 04 · PEGANDEKAN</span><h1>{data[page]?.[0]||page}</h1><p>{data[page]?.[1]}</p></div><button className="secondary" onClick={()=>go("Beranda")}><Icon name="fa-arrow-left"/> Kembali</button></div>
 {page==="Komunitas"?<Community tab={tab} setTab={setTab} comment={comment} setComment={setComment} sent={sent} setSent={setSent}/>:<Generic page={page}/>}
 </div></section>
}
function Community({tab,setTab,comment,setComment,sent,setSent}:{tab:string,setTab:any,comment:string,setComment:any,sent:boolean,setSent:any}){
 const tabs=[["Feed Warga","fa-house"],["Story 24h","fa-circle-play"],["Aspirasi","fa-lightbulb"],["Diskusi","fa-comments"],["Polling","fa-square-poll-vertical"]] as const;
 const stories=[["BS","Budi","fa-mountain-sun"],["SA","Siti","fa-seedling"],["AR","Agus","fa-person"],["RN","Rina","fa-house"],["DN","Doni","fa-champagne-glasses"]];
 const feed=[
  {name:"Budi Santoso",initial:"BS",time:"18 menit",text:"Ngikutin trend jajanan warga. Ada yang punya rekomendasi jajanan enak di sekitar Pegandekan?",image:"https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1000&q=80",likes:55,comments:14,shares:19},
  {name:"Reno Bangkit",initial:"RB",time:"13 jam",text:"Kang, aku bikin koleksi processing terus ya? Solusi dong",image:"",likes:1,comments:1,shares:0},
  {name:"Parkseujung",initial:"PK",time:"14 jam",text:"Kuntinya diamant dulu ya, rambutnya panjang setelah joget rambut pendek, emang beda",image:"",likes:0,comments:2,shares:0},
  {name:"Deden Saputra",initial:"DS",time:"6 jam",text:"Bayar yang generate nya.",image:"",likes:0,comments:0,shares:0},
  {name:"Rifqi_mr",initial:"RM",time:"12 jam",text:"Rambut panjang jadi pendek, daster jadi jas. Apakah kurang prompt?",image:"",likes:0,comments:0,shares:0},
  {name:"Kenangadewi27",initial:"KD",time:"9 jam",text:"bikin kaya gini gimana pengen juga hu hu",image:"",likes:0,comments:0,shares:0},
  {name:"ra_irsad",initial:"RI",time:"8 jam",text:"prompt dng",image:"",likes:0,comments:0,shares:0}
 ];
 return <div className="communityShell">
  <div className="communityTop">
   <div className="communityTitle"><div className="communityAvatar"><Icon name="fa-users"/></div><div><b>Komunitas Warga</b><small>RT 01 / RW 04 · Pegandekan</small></div></div>
   <button className="communitySearch"><Icon name="fa-magnifying-glass"/> Cari</button>
  </div>
  <div className="communityTabs">{tabs.map(([t,ic])=><button className={tab===t?"selected":""} onClick={()=>setTab(t)} key={t}><Icon name={ic}/><span>{t}</span></button>)}</div>
  {tab==="Story 24h" ? <div className="communityCard storyPanel"><div className="panelTitle"><b>Story Warga</b><small>Berlangsung 24 jam</small></div><div className="stories">{stories.map(([initial,name,ic],i)=><div className="story" key={name}><div className="storyRing"><div className="storyIcon"><Icon name={ic}/></div></div><b>{name}</b><small>{i+3}j</small></div>)}</div></div>
  : tab==="Aspirasi" ? <div className="communityCard aspirationPanel"><div className="panelTitle"><b>Aspirasi Warga</b><button><Icon name="fa-plus"/> Buat aspirasi</button></div><div className="aspirationItem"><div><span className="status"><Icon name="fa-clock"/> DITINJAU</span><h3>Perbaikan lampu jalan</h3><p>Beberapa titik penerangan perlu diperiksa.</p></div><div className="timeline"><span>✓ Diajukan</span><span>● Ditinjau</span><span>○ Dikoordinasikan</span><span>○ Selesai</span></div></div><div className="aspirationItem"><div><span className="status done"><Icon name="fa-circle-check"/> SELESAI</span><h3>Saluran air depan balai</h3><p>Pembersihan telah selesai dilakukan.</p></div><div className="timeline"><span>✓ Diajukan</span><span>✓ Ditinjau</span><span>✓ Dikerjakan</span><span>✓ Selesai</span></div></div></div>
  : tab==="Polling" ? <div className="communityCard poll"><div className="panelTitle"><div><span className="eyebrow"><Icon name="fa-square-poll-vertical"/> POLLING WARGA</span><h2>Usulan kegiatan bulan depan?</h2></div></div>{["Kerja bakti","Senam pagi","Lomba antar-RT","Pelatihan UMKM"].map((x,i)=><button key={x} className="pollOpt"><span>{x}</span><b>{[42,26,19,13][i]}%</b></button>)}</div>
  : tab==="Diskusi" ? <div className="communityCard discussion"><div className="panelTitle"><b>Diskusi Warga</b><button><Icon name="fa-plus"/> Topik baru</button></div><div className="discussionItem"><Icon name="fa-comments"/><div><b>Persiapan kerja bakti Minggu</b><p>8 balasan · aktif 12 menit lalu</p></div><span>›</span></div><div className="discussionItem"><Icon name="fa-comments"/><div><b>Ide kegiatan pemuda RT</b><p>14 balasan · aktif 1 jam lalu</p></div><span>›</span></div></div>
  : <div className="feedColumn">
    <div className="composer communityCard"><div className="composerAvatar">BS</div><div className="composerInput">Apa yang ingin kamu bagikan, warga?</div><div className="composerTools"><button><Icon name="fa-image"/> Foto/Video</button><button><Icon name="fa-face-smile"/> Perasaan</button><button><Icon name="fa-bullhorn"/> Aspirasi</button></div></div>
    <div className="communityCard storyStrip"><div className="storyAdd"><div className="storyAddIcon"><Icon name="fa-plus"/></div><b>Buat Story</b><small>24 jam</small></div>{stories.slice(1).map(([initial,name,ic])=><div className="storyMini" key={name}><div className="storyMiniBg"><Icon name={ic}/></div><b>{name}</b></div>)}</div>
    {feed.map((p,i)=><article className="communityCard socialPost" key={p.name+i}>
      <div className="socialHeader"><div className="socialAvatar">{p.initial}</div><div className="socialIdentity"><b>{p.name}</b><small>{p.time} · <Icon name="fa-earth-asia"/></small></div><button className="more"><Icon name="fa-ellipsis"/></button></div>
      <p className="socialText">{p.text}</p>
      {p.image&&<div className="postImage"><img src={p.image} alt="Kiriman warga"/></div>}
      <div className="postStats"><span><Icon name="fa-heart"/> {p.likes}</span><span>{p.comments} komentar · {p.shares} dibagikan</span></div>
      <div className="socialActions"><button><Icon name="fa-heart"/> Suka</button><button><Icon name="fa-comment"/> Komentar</button><button><Icon name="fa-share"/> Bagikan</button></div>
      <div className="commentTop"><span>↕ Terbaru</span><button>Lihat aktivitas</button></div>
      {i===0&&<div className="socialComment"><div className="commentAvatar">RB</div><div><b>Reno Bangkit</b><small>13 jam</small><p>Kang, aku bikin koleksi processing terus ya? Solusi dong</p><div className="commentActions"><span><Icon name="fa-heart"/> 1</span><span><Icon name="fa-reply"/> Balas</span><span>Terjemahkan</span></div></div></div>}
      <div className="commentInput"><div className="commentAvatar">BS</div><input value={comment} onChange={e=>setComment(e.target.value)} placeholder={"Balas ke "+p.name+"..."} /><button onClick={()=>{setSent(true);setComment("")}}><Icon name="fa-paper-plane"/></button></div>
      {sent&&i===0&&<small className="sent">Komentar berhasil dikirim.</small>}
    </article>)}
  </div>}
 </div>
}
function Generic({page}:{page:string}){const cards={Profil:["fa-users","Pengurus RT","Ketua RT · Sekretaris · Bendahara · Koordinator"],Informasi:["fa-circle-info","Informasi Terkini","Pengumuman resmi, berita warga, dan arsip informasi."],Kegiatan:["fa-calendar-days","Agenda Mendatang","Kerja bakti · Rapat warga · Posyandu · Olahraga"],Layanan:["fa-file-signature","Ajukan Layanan","Surat pengantar, pengaduan, aspirasi, dan administrasi warga."],Pengumuman:["fa-bullhorn","Pengumuman Resmi","Notifikasi penting dari pengurus RT."],Galeri:["fa-images","Dokumentasi","Foto kegiatan, lingkungan, dan kebersamaan warga."],Kontak:["fa-location-dot","Hubungi Pengurus","WhatsApp · Email · Lokasi balai RT"]};const c:any=cards[page as keyof typeof cards]||["fa-wand-magic-sparkles",page,"Fitur siap dikembangkan"];return <div className="grid3"><div className="featureCard"><span><Icon name={c[0]}/></span><h2>{c[1]}</h2><p>{c[2]}</p><button className="primary">Buka fitur <Icon name="fa-arrow-right"/></button></div><div className="featureCard"><span><Icon name="fa-shield-halved"/></span><h2>Akun & Keamanan</h2><p>Email verification · Google login · role warga/admin · moderasi.</p><button className="secondary">Pengaturan</button></div><div className="featureCard"><span><Icon name="fa-mobile-screen-button"/></span><h2>PWA</h2><p>Install ke perangkat, tampilan responsif, cache offline, dan siap notifikasi.</p><button className="secondary">Install App <Icon name="fa-download"/></button></div></div>}
